---
- name: Deploy Application with Docker
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:

    - name: Remove old Docker container if exists
      command: docker rm -f web
      ignore_errors: yes

    - name: Remove old Docker image if exists
      command: docker rmi -f sinchana1231/webapp:latest
      ignore_errors: yes

    - name: Log in to Docker Hub
      command: echo "Mydocker@12" | docker login -u sinchana1231 --password-stdin

    - name: Pull Docker Image from Docker Hub
      command: docker pull sinchana1231/webapp:latest

    - name: Run Docker Container
      command: docker run -it -d --name web -p 8081:8080 sinchana1231/webapp:latest
